package com.jt.bookingschedule.model;

public enum ServiceType {

    MANICURE_FRENCH_GEL,
    PEDICURE_FRENCH_GEL,
    MANICURE_REPAIR_MAINTENANCE,
    PEDICURE_REPAIR_MAINTENANCE,
    MANICURE_WITH_STRENGTHENING,
    MANICURE_WITHOUT_POLISHING
}
